#!/usr/bin/env python3
"""The list of claims (Document 6, Working Method, point 7): the test names of engine, rules and web.security, one
sentence per test, which the presenter reads before each rehearsal as what may be claimed in the interview.

A test is a method annotated @Test, @ParameterizedTest or @Property (jqwik); its name becomes the sentence, a
parameterized test and a property say so. The list follows the source: a package, then each test class in path order,
then its tests in the order they are written.

Run:
  python3 scripts/ci/claims.py              write docs/quality/claims.md
  python3 scripts/ci/claims.py --check      CI stage 1: exit 1 when the committed list is not the regeneration
  python3 scripts/ci/claims.py --self-test
"""
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LIST = Path("docs/quality/claims.md")
TESTS = Path("backend/src/test/java/com/liorshaya/policypilot")
PACKAGES = ("engine", "rules", "web/security")

ANNOTATION = re.compile(r"^\s*@(Test|ParameterizedTest|Property)\b")
METHOD = re.compile(r"^\s*(?:public\s+|protected\s+)?void\s+(\w+)\s*\(")
KIND = {"ParameterizedTest": " (parameterized)", "Property": " (property)"}
# a word boundary inside a camel-case name: before a capital that follows a lower case letter or a digit, inside a
# run of capitals before the capital that starts the next word, and before a number
WORD = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])|(?<=[a-zA-Z])(?=[0-9])")


def sentence(name):
    """{@code twentiethFailureLocksForFifteenMinutes} as "Twentieth failure locks for fifteen minutes"; an acronym
    such as ASCII keeps its capitals."""
    words = [w if len(w) > 1 and w.isupper() else w.lower() for w in WORD.sub(" ", name).split()]
    first = words[0]
    return " ".join([first[:1].upper() + first[1:]] + words[1:])


def tests_of(source):
    """The tests of one Java source, in order, each as its sentence."""
    found, pending = [], None
    for line in source.splitlines():
        annotation = ANNOTATION.match(line)
        if annotation:
            pending = annotation.group(1)
            continue
        method = METHOD.match(line)
        if method and pending:
            found.append(sentence(method.group(1)) + KIND.get(pending, ""))
            pending = None
    return found


def render(root):
    """The list as Markdown, and the number of tests in it."""
    sections, total = [], 0
    for package in PACKAGES:
        classes = []
        for path in sorted((root / TESTS / package).rglob("*.java")):
            tests = tests_of(path.read_text(encoding="utf-8"))
            if tests:
                name = ".".join(path.relative_to(root / TESTS / package).with_suffix("").parts)
                classes.append((name, tests))
        count = sum(len(tests) for _, tests in classes)
        total += count
        sections.append(f"## {package.replace('/', '.')} ({count} test{'' if count == 1 else 's'})")
        for name, tests in classes:
            sections.append(f"### {name}\n\n" + "\n".join(f"- {test}" for test in tests))
    head = [
        "# The list of claims",
        "",
        "Generated by `scripts/ci/claims.py` from the test sources (Document 6, Working Method, point 7): every "
        f"test of `engine`, `rules` and `web.security`, {total} in all, one sentence each. Read before each rehearsal "
        "as what may be claimed in the interview; do not edit by hand.",
    ]
    return "\n\n".join(["\n".join(head)] + sections) + "\n", total


def main(argv):
    if argv[1:] == ["--self-test"]:
        return self_test()
    text, total = render(ROOT)
    if argv[1:] == ["--check"]:
        committed = ROOT / LIST
        if not committed.is_file() or committed.read_text(encoding="utf-8") != text:
            print(f"{LIST} is not the regeneration: run python3 scripts/ci/claims.py and commit it")
            return 1
        print(f"list of claims OK ({total} tests)")
        return 0
    if argv[1:]:
        print(__doc__)
        return 2
    (ROOT / LIST).parent.mkdir(parents=True, exist_ok=True)
    (ROOT / LIST).write_text(text, encoding="utf-8")
    print(f"written {LIST}: {total} tests")
    return 0


def self_test():
    """The generator on a small tree of its own: every annotation, a nested package, a helper that is no test."""
    expected_names = {
        "twentiethFailureLocksForFifteenMinutes": "Twentieth failure locks for fifteen minutes",
        "div128RoundsHalfEven": "Div 128 rounds half even",
        "asciiIsKeptButNFCIsApplied": "Ascii is kept but NFC is applied",
        "a": "A",
    }
    failures = [f"sentence({name!r}) is {sentence(name)!r}, expected {want!r}"
                for name, want in expected_names.items() if sentence(name) != want]
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        files = {
            TESTS / "engine/RuleEngineTest.java":
                "class RuleEngineTest {\n  @Test\n  void firstRuleFires() {}\n\n  private void helper() {}\n\n"
                "  @ParameterizedTest(name = \"{0}\")\n  @ValueSource(ints = {1})\n  void eachCaseDecides(int n) {}\n"
                "  @Property(seed = SEED)\n  void neverThrows(@ForAll int n) {}\n}\n",
            TESTS / "rules/patch/PatchValidatorTest.java":
                "class PatchValidatorTest {\n  @Test\n  void rejectsIt() {}\n}\n",
            TESTS / "rules/support/Builders.java": "class Builders {\n  void build() {}\n}\n",
            TESTS / "web/security/SessionIT.java":
                "class SessionIT {\n  @Test\n  public void expiredCookieReturns401() {}\n}\n",
            TESTS / "ai/NotListedTest.java": "class NotListedTest {\n  @Test\n  void outsideTheThreePackages() {}\n}\n",
        }
        for path, content in files.items():
            (root / path).parent.mkdir(parents=True, exist_ok=True)
            (root / path).write_text(content, encoding="utf-8")
        text, total = render(root)
        want = [
            "## engine (3 tests)", "### RuleEngineTest", "- First rule fires", "- Each case decides (parameterized)",
            "- Never throws (property)", "## rules (1 test)", "### patch.PatchValidatorTest", "- Rejects it",
            "## web.security (1 test)", "### SessionIT", "- Expired cookie returns 401",
        ]
        lines = text.split("\n")
        failures += [f"missing line {line!r}" for line in want if line not in lines]
        if total != 5:
            failures.append(f"{total} tests, expected 5")
        for unwanted in ("Helper", "Build", "Outside the three packages", "Builders"):
            if unwanted in text:
                failures.append(f"{unwanted!r} is listed, and it is no test of the three packages")
    for failure in failures:
        print("SELF-TEST FAILED:", failure)
    if not failures:
        print("claims self-test: ALL OK")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
