#!/usr/bin/env python3
"""The traceability matrix (Document 6, Traceability Matrix): each requirement of the Brief and the tests that prove it.

The requirements are read from the Brief's two tables (FR-n and NFR-n); the tests from their tags: @Requirement("FR-8")
or @Requirement({"FR-7", "NFR-3"}) on a JUnit class or method, and a `// @requirement FR-13` line in a Vitest or
Playwright file (one id a line, the file's tests all prove it). Each test lands in the matrix's column for its level:

  Unit and conformance                 JUnit *Test, Vitest
  Integration and contract             JUnit *IT
  Recorded AI, evaluation, red team    JUnit Recorded*IT, Eval*IT and RedTeam*IT
  End to end                           Playwright

Run:
  python3 scripts/ci/traceability.py            write docs/quality/traceability.md
  python3 scripts/ci/traceability.py --check    CI stage 1: exit 1 when the committed matrix is not the regeneration,
                                                or when a requirement has no test and is not listed in OPEN below
  python3 scripts/ci/traceability.py --summary  CI stage 8: the matrix for the job summary
  python3 scripts/ci/traceability.py --self-test
"""
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BRIEF = Path("docs/01-project-brief.md")
MATRIX = Path("docs/quality/traceability.md")
JAVA_TESTS = Path("backend/src/test/java")
FRONTEND = (Path("frontend/src"), Path("frontend/e2e"))

# Requirements whose row may still be empty: the Work Plan closes them by day 16 ("the traceability matrix has no
# empty row", Definition of Done). The list only shrinks; day 15 (gate G3) requires FR-17 to FR-20, which have tests.
OPEN = {"FR-2", "FR-16", "FR-21", "NFR-4"}

COLUMNS = ("Unit and conformance", "Integration and contract", "Recorded AI, evaluation, red team", "End to end")
RECORDED = re.compile(r"^(Recorded|Eval|RedTeam)\w*IT$")
JAVA_TAG = re.compile(r'@Requirement\(\s*(\{[^}]*\}|"[^"]*")\s*\)')
JAVA_DECLARATION = re.compile(r"\b(?:class|record|interface)\s+(\w+)|\b\w[\w<>,\s]*\s+(\w+)\s*\(")
TS_TAG = re.compile(r"^\s*//\s*@requirement\s+((?:N?FR)-\d+)\s*$", re.M)
BRIEF_ROW = re.compile(r"^\| ((?:N?FR)-\d+) \| ([^|]+) \|", re.M)


def requirements(root):
    """The Brief's requirement ids in order, each with its text (FR) or its name (NFR)."""
    return [(rid, text.strip()) for rid, text in BRIEF_ROW.findall((root / BRIEF).read_text(encoding="utf-8"))]


def java_tags(path):
    """(requirement, test name) for every tag of a JUnit file: the class, or Class.method for a tagged method."""
    text = path.read_text(encoding="utf-8")
    found = []
    for tag in JAVA_TAG.finditer(text):
        ids = re.findall(r'"([^"]+)"', tag.group(1))
        declaration = JAVA_DECLARATION.search(text, tag.end())
        name = path.stem if declaration is None or declaration.group(1) else f"{path.stem}.{declaration.group(2)}"
        found += [(rid, name) for rid in ids]
    return found


def column_of_java(path):
    if RECORDED.match(path.stem):
        return 2
    return 1 if path.stem.endswith("IT") else 0


def collect(root):
    """{requirement: [set of test names per column]} from every tagged test under root."""
    cells = {}

    def add(rid, column, name):
        cells.setdefault(rid, [set() for _ in COLUMNS])[column].add(name)

    for path in sorted((root / JAVA_TESTS).rglob("*.java")):
        for rid, name in java_tags(path):
            add(rid, column_of_java(path), name)
    for base in FRONTEND:
        for path in sorted((root / base).rglob("*.ts*")) if (root / base).is_dir() else []:
            if not re.search(r"\.(test|spec)\.tsx?$", path.name):
                continue
            column = 3 if path.name.endswith((".spec.ts", ".spec.tsx")) and "e2e" in path.parts else 0
            for rid in TS_TAG.findall(path.read_text(encoding="utf-8")):
                add(rid, column, path.name)
    return cells


def render(root):
    rows = requirements(root)
    cells = collect(root)
    unknown = sorted(set(cells) - {rid for rid, _ in rows})
    empty = [rid for rid, _ in rows if not any(cells.get(rid, ()))]
    lines = [
        "# Traceability Matrix",
        "",
        "Generated by `scripts/ci/traceability.py` from the tests' requirement tags (Document 6, Traceability Matrix);",
        "never edited by hand. Each cell names the test classes, methods or files that prove the requirement.",
        "",
        f"{len(rows) - len(empty)} of {len(rows)} requirements have at least one test"
        + (f"; empty: {', '.join(empty)}." if empty else "."),
        "",
        "| Requirement | " + " | ".join(COLUMNS) + " |",
        "| --- |" + " --- |" * len(COLUMNS),
    ]
    for rid, text in rows:
        columns = cells.get(rid, [set() for _ in COLUMNS])
        lines.append(f"| {rid} {text} | " + " | ".join(", ".join(sorted(c)) for c in columns) + " |")
    if unknown:
        lines += ["", f"Tags naming no requirement of the Brief: {', '.join(unknown)}."]
    return "\n".join(lines) + "\n", empty, unknown


def problems(root, open_rows):
    """What --check reports: a stale committed matrix, an empty row not listed as open, an open row that has tests
    now, and a tag that names no requirement."""
    text, empty, unknown = render(root)
    committed = root / MATRIX
    found = []
    if not committed.is_file() or committed.read_text(encoding="utf-8") != text:
        found.append(f"{MATRIX} is not the regeneration: run python3 scripts/ci/traceability.py and commit it")
    found += [f"{rid} has no test, and it is not among the rows still open" for rid in empty if rid not in open_rows]
    found += [f"{rid} is listed as open but has tests now: take it off OPEN" for rid in sorted(open_rows)
              if rid not in empty]
    found += [f"a test is tagged {rid}, which the Brief does not have" for rid in unknown]
    return found, empty


def main(argv):
    if argv[1:] == ["--self-test"]:
        return self_test()
    if argv[1:] == ["--summary"]:
        print(render(ROOT)[0])
        return 0
    if argv[1:] == ["--check"]:
        found, empty = problems(ROOT, OPEN)
        for problem in found:
            print(problem)
        if not found:
            print(f"traceability matrix OK ({len(empty)} open rows: {', '.join(empty) or 'none'})")
        return 1 if found else 0
    if argv[1:]:
        print(__doc__)
        return 2
    text, empty, _ = render(ROOT)
    (ROOT / MATRIX).parent.mkdir(parents=True, exist_ok=True)
    (ROOT / MATRIX).write_text(text, encoding="utf-8")
    print(f"written {MATRIX}; empty rows: {', '.join(empty) or 'none'}")
    return 0


def self_test():
    """The generator on a small tree of its own: every tag form, every column, an empty row and an unknown id."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        files = {
            BRIEF: "| FR-1 | Paste a policy | Must |\n| FR-2 | Generate | Must |\n| NFR-1 | Determinism | same |\n",
            JAVA_TESTS / "a/PasteTest.java": '@Requirement("FR-1")\nclass PasteTest {\n  @Test void one() {}\n}\n',
            JAVA_TESTS / "a/PasteIT.java": 'class PasteIT {\n  @Test\n  @Requirement({"FR-1", "NFR-1"})\n'
                                           '  void storesIt() {}\n}\n',
            JAVA_TESTS / "a/RecordedPasteIT.java": '@Requirement("FR-1")\nclass RecordedPasteIT {}\n',
            JAVA_TESTS / "a/StrayTest.java": '@Requirement("FR-99")\nclass StrayTest {}\n',
            Path("frontend/src/paste.test.tsx"): "// @requirement FR-1\n// @requirement NFR-1\nit('x')\n",
            Path("frontend/src/paste.tsx"): "// @requirement FR-2\n",
            Path("frontend/e2e/paste.spec.ts"): "// @requirement FR-1\n",
        }
        for path, content in files.items():
            (root / path).parent.mkdir(parents=True, exist_ok=True)
            (root / path).write_text(content, encoding="utf-8")
        text, empty, unknown = render(root)
        expected_rows = [
            "| FR-1 Paste a policy | PasteTest, paste.test.tsx | PasteIT.storesIt | RecordedPasteIT | paste.spec.ts |",
            "| FR-2 Generate |  |  |  |  |",
            "| NFR-1 Determinism | paste.test.tsx | PasteIT.storesIt |  |  |",
        ]
        failures = [row for row in expected_rows if row not in text.split("\n")]
        if empty != ["FR-2"]:
            failures.append(f"empty rows {empty}, expected ['FR-2'] (a tag in a file that is not a test counts not)")
        if unknown != ["FR-99"]:
            failures.append(f"unknown ids {unknown}, expected ['FR-99']")
        (root / MATRIX).parent.mkdir(parents=True)
        (root / MATRIX).write_text(text, encoding="utf-8")
        checks = {
            "current, FR-2 open": (problems(root, {"FR-2"})[0], []),
            "FR-2 empty and not open": (problems(root, set())[0],
                                        ["FR-2 has no test, and it is not among the rows still open"]),
            "FR-1 open though tested": (problems(root, {"FR-1", "FR-2"})[0],
                                        ["FR-1 is listed as open but has tests now: take it off OPEN"]),
        }
        (root / MATRIX).write_text(text.replace("PasteTest", "OldTest"), encoding="utf-8")
        checks["stale matrix"] = (problems(root, {"FR-2"})[0],
                                  [f"{MATRIX} is not the regeneration: run python3 scripts/ci/traceability.py and "
                                   "commit it"])
        for name, (found, expected) in checks.items():
            found = [problem for problem in found if "FR-99" not in problem]
            if found != expected:
                failures.append(f"check {name}: {found}, expected {expected}")
        for failure in failures:
            print("SELF-TEST FAILED:", failure)
        if not failures:
            print("traceability self-test: ALL OK")
        return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
